apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-jenkins
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
